spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/selfexam
    username: root
    password: root1234
    driver-class-name: org.mariadb.jdbc.Driver
    initialization-mode: always
  jpa:
    generate-ddl: false

---

spring:
  profiles: test
  datasource:
    url: jdbc:mariadb://localhost:3306/selfexamtest
    username: root
    password: root1234
    driver-class-name: org.mariadb.jdbc.Driver