spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/selfexam
    username: root
    password: root1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true

---

spring:
  profiles: test
  datasource:
    url: jdbc:mariadb://localhost:3306/selfexamtest
    username: root
    password: root1234
    driver-class-name: org.mariadb.jdbc.Driver