name: Server build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.4.8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root1234
          MYSQL_DATABASE: selfexam

    defaults:
      run:
        working-directory: servers
    steps:
      - uses: actions/checkout@v2
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop
      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 14.0.1
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew build
      - name: Test
        run: ./gradlew test

